db8abase/db8abase/Models/TournamentDirector.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace db8abase.Models
{
    public class TournamentDirector
    {
        [Key]
        public int TournamentDirectorId { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set;}
        [Display(Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }
        public string Message { get; set; }
        [ForeignKey("Tournament Id")]
        public int TournamentId { get; set; }
        [ForeignKey("User Id")]
        public string ApplicationUserId { get; set; }
        [ForeignKey("School Id")]
        public int SchoolId { get; set; }
        public string FilePath { get; set; }
    }
}

db8abase/db8abase/Controllers/RoomsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;
using db8abase.Data;
using db8abase.Models;
using Microsoft.AspNetCore.Mvc;

namespace db8abase.Controllers
{
    public class RoomsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public RoomsController(ApplicationDbContext context)
        {
            _context = context;
        }
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Create()
        {
            Room room = new Room();
            return View(room);
        }
        [HttpPost]
        public IActionResult Create([Bind("RoomId,RoomNumber,SchoolId")] Room room)
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            room.SchoolId = currentDirector.SchoolId;
            _context.Add(room);
            _context.SaveChanges();
            return RedirectToAction("GetRoomsList", "TournamentDirectors");
        }
    }
}

db8abase/db8abase/Controllers/TournamentDirectorsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using db8abase.Data;
using db8abase.Models;
using System.Security.Claims;
using Microsoft.AspNetCore.Http;
using System.IO;
using db8abase.Models.ViewModels;

namespace db8abase.Controllers
{
    public class TournamentDirectorsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public TournamentDirectorsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: TournamentDirectors
        public async Task<IActionResult> Index()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var tournamentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            return View(tournamentDirector);
        }

        // GET: TournamentDirectors/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var tournamentDirector = await _context.TournamentDirector
                .FirstOrDefaultAsync(m => m.TournamentDirectorId == id);
            if (tournamentDirector == null)
            {
                return NotFound();
            }

            return View(tournamentDirector);
        }

        // GET: TournamentDirectors/Create
        public IActionResult Create()
        {
            TournamentDirector TournamentDirector = new TournamentDirector();
            return View(TournamentDirector);
        }

        // GET: TournamentDirectors/SelectSchool
        public IActionResult SelectSchool(int Id)
        {
            School school = _context.School.FirstOrDefault(s => s.SchoolId == Id);
            return View(school);
        }
        
        public IActionResult SelectSchool([Bind("SchoolId")] TournamentDirector tournamentDirector, int id)
        {
            var selectedSchool = _context.School.FirstOrDefault(s => s.SchoolId == id);
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            tournamentDirector = currentDirector;
            tournamentDirector.SchoolId = selectedSchool.SchoolId;
            _context.Attach(tournamentDirector);
            _context.SaveChanges();
            return RedirectToAction("Index", "TournamentDirectors");
        }

        public IActionResult GetRoomsList()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            var roomList = _context.Room.Where(r => r.SchoolId == currentDirector.SchoolId).ToList();
            return View(roomList);
        }

        public IActionResult TournamentPortal()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == currentDirector.TournamentId);
            Pairing pairing = _context.Pairing.FirstOrDefault(p => p.TournamentId == tournament.TournamentId);
            List<Round> rounds = _context.Round.Where(t => t.TournamentId == tournament.TournamentId).ToList();
            List<Round> roundsInOrder = rounds.OrderByDescending(r => r.RoundNumber).ToList();
            List<Debater> awards = new List<Debater>();
            if(roundsInOrder.Count() > 0)
            {
                List<Debater> speakerAwards = SpeakerAwardsList(tournament.TournamentId, roundsInOrder);
                foreach(var award in speakerAwards)
                {
                    awards.Add(award);
                }
            }
            Round round = new Round();
            if(rounds.Count() == 0)
            {
                round = null;
            }
            else
            {
                round = roundsInOrder[0];
            }


            DirectorsTournamentPortalViewModel portalVM = new DirectorsTournamentPortalViewModel()
            {
                Tournament = tournament,
                Rounds = rounds,
                Round = round,
                SpeakerAwards = awards,
            };
            return View(portalVM);
        }
        public IActionResult DisplaySpeakerAwards(int id)
        {
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
            List<Round> rounds = _context.Round.Where(t => t.TournamentId == tournament.TournamentId).ToList();
            List<Round> roundsInOrder = rounds.OrderByDescending(r => r.RoundNumber).ToList();
            List<Debater> speakerAwards = SpeakerAwardsList(id, roundsInOrder);
            List<School> schools = GetSpeakerAwardSchools(speakerAwards);
            List<int> rankings = CreateRankings();

            PairingsSpeakerPointsViewModel data = new PairingsSpeakerPointsViewModel()
            {
                Tournament = tournament,
                Ranking = rankings,
                Schools = schools,
                SpeakerAwards = speakerAwards,
            };
            return View(data);
        }
        public IActionResult CompleteSpeakerAwards(int id)
        {
            List<IndividualTeam> teams = GetTeams(id);
            List<Debater> debaters = new List<Debater>();
            foreach(var team in teams)
            {
                Debater debater1 = _context.Debater.FirstOrDefault(d => d.DebaterId == team.FirstSpeakerId);
                Debater debater2 = _context.Debater.FirstOrDefault(d => d.DebaterId == team.SecondSpeakerId);
                debaters.Add(debater1);
                debaters.Add(debater2);
            }
            foreach(var debater in debaters)
            {
                int numberOfTournaments = _context.TeamEntry.Where(t => t.IndividualTeamId == debater.IndividualTeamId).ToList().Count();
                debater.AnnualAverageSpeakerPoints = (((debater.AnnualAverageSpeakerPoints * (numberOfTournaments - 1)) + debater.IndividualTournamentSpeakerPoints) / numberOfTournaments);
                debater.IndividualTournamentSpeakerPoints = 0;
                _context.Update(debater);
                _context.SaveChanges();
            }
            return View();
        }
        
        public List<int> CreateRankings()
        {
            List<int> rankings = new List<int>();
            int speakerThreshold = 10;
            int count = 0;
            for(int i = 0; i < speakerThreshold; i++)
            {
                count++;
                rankings.Add(count);
            }
            return rankings;
        }

        public List<School> GetSpeakerAwardSchools(List<Debater> speakers)
        {
            List<School> schools = new List<School>();
            foreach(var speaker in speakers)
            {
                School school = _context.School.FirstOrDefault(s => s.SchoolId == speaker.SchoolId);
                schools.Add(school);
            }
            return schools;
        }

        public List<Debater> SpeakerAwardsList(int id, List<Round> roundsInOrder)
        {
            if (roundsInOrder[0].RoundNumber == 4)
            {
                Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
                List<IndividualTeam> teams = GetTeams(id);
                List<Debater> debaters = new List<Debater>();
                List<Debater> speakerAwards = new List<Debater>();
                List<Debater> emptyList = new List<Debater>();
                int speakerAwardThreshold = 10;
                foreach (var team in teams)
                {
                    Debater debater1 = _context.Debater.FirstOrDefault(d => d.DebaterId == team.FirstSpeakerId);
                    Debater debater2 = _context.Debater.FirstOrDefault(d => d.DebaterId == team.SecondSpeakerId);
                    debaters.Add(debater1);
                    debaters.Add(debater2);
                }
                List<Debater> speakerRankings = debaters.OrderByDescending(d => d.IndividualTournamentSpeakerPoints).ToList();
                for (int i = 0; i < speakerAwardThreshold; i++)
                {
                    speakerAwards.Add(speakerRankings[i]);
                }
                if(speakerAwards[0].IndividualTournamentSpeakerPoints == 0)
                {
                    return emptyList;
                }
                else
                {
                    return speakerAwards;
                }
            }
            else
            {
                List<Debater> fakeList = new List<Debater>();
                return fakeList;
            }
        }
        public List<IndividualTeam> GetTeams(int id)
        {
            List<IndividualTeam> teams = new List<IndividualTeam>();
            var entries = _context.TeamEntry.Where(t => t.TournamentId == id).ToList();
            var individualTeams = _context.IndividualTeam.ToList();
            foreach (var entry in entries)
            {
                for (int i = 0; i < individualTeams.Count; i++)
                {
                    if (entry.IndividualTeamId == individualTeams[i].IndividualTeamId)
                    {
                        var locatedTeam = _context.IndividualTeam.FirstOrDefault(t => t.IndividualTeamId == individualTeams[i].IndividualTeamId);
                        teams.Add(locatedTeam);
                    }
                }
            }
            return teams;
        }

db8abase/db8abase/Views/TournamentDirectors/CompleteSpeakerAwards.cshtml
@{
    ViewData["Title"] = "CompleteSpeakerAwards";
}
<br />
<br />
<h1>Thank you for submitting the speaker awards</h1>
<br />
<br />
<p>Click below to return to the tournament portal</p>
<br />
<p>
    <a asp-controller="TournamentDirectors" asp-action="TournamentPortal" style="color:#087485">Return to Portal</a>
</p>

db8abase/db8abase/Views/TournamentDirectors/Create.cshtml
@model db8abase.Models.TournamentDirector

@{
    ViewData["Title"] = "Create";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Create New Account</h1>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TournamentDirectorId" />
            <input type="hidden" asp-for="ApplicationUserId" />
            <input type="hidden" asp-for="Message" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/TournamentDirectors/CreateTournament.cshtml
@model db8abase.Models.Tournament

@{
    ViewData["Title"] = "CreateTournament";
}
<br />
<h1>Create Tournament</h1>
<br />
<h5>Be sure to upload tournament invitation BEFORE clicking create</h5>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateTournament">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TournamentId" />
            <input type="hidden" asp-for="NumberOfEliminationRounds" />
            <input type="hidden" asp-for="FilePath" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NumberOfRounds" class="control-label"></label>
                <input asp-for="NumberOfRounds" class="form-control" />
                <span asp-validation-for="NumberOfRounds" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="EntryFee" class="control-label"></label>
                <input asp-for="EntryFee" class="form-control" />
                <span asp-validation-for="EntryFee" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TournamentDate" class="control-label"></label>
                <input asp-for="TournamentDate" class="form-control" />
                <span asp-validation-for="TournamentDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TeamLimit" class="control-label"></label>
                <input asp-for="TeamLimit" class="form-control" />
                <span asp-validation-for="TeamLimit" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<div class="row">
    <div class="col-sm-12">
        <form method="post" enctype="multipart/form-data" asp-controller="FileUpload" asp-action="Index">
            <div class="form-group">
                <div class="col-sm-10">
                    <p> Upload invitation files by choosing files and then clicking upload:</p>
                    <input type ="file" name="files" multiple />
                </div>
            </div>
            <div class="form-group">
                <div class="col-sm-10">
                    <input type="submit" value="Upload" class="btn btn-primary"/>
                </div>
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/TournamentDirectors/Delete.cshtml
@model db8abase.Models.TournamentDirector

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>TournamentDirector</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="TournamentDirectorId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

db8abase/db8abase/Views/TournamentDirectors/Details.cshtml
@model db8abase.Models.TournamentDirector

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>TournamentDirector</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Message)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Message)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.TournamentDirectorId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/TournamentDirectors/DisplaySpeakerAwards.cshtml
@model db8abase.Models.ViewModels.PairingsSpeakerPointsViewModel
@{
    ViewData["Title"] = "DisplaySpeakerAwards";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Speaker Awards for @Model.Tournament.Name</h1>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                Rank
            </th>
            <th>
                Speaker
            </th>
            <th>
                School
            </th>
            <th>
                Points
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.SpeakerAwards.Count(); i++)
        {
            <tr class="table-secondary">
                <th scope="row">
                    @Html.DisplayFor(model => model.Ranking[i])
                </th>
                <td>
                    @Html.DisplayFor(model => model.SpeakerAwards[i].FirstName) @Html.DisplayFor(model => model.SpeakerAwards[i].LastName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Schools[i].Name)
                </td>
                <td>
                    @Html.DisplayFor(model => model.SpeakerAwards[i].IndividualTournamentSpeakerPoints)
                </td>
            </tr>
        }
    </tbody>
</table>
<br />
<p>All speaker awards are listed above.  Please print this page for your reference.</p>
<p>Click below in order to submit speaker awards.</p>
<p>
    <a asp-controller="TournamentDirectors" asp-action="CompleteSpeakerAwards" asp-route-id="@Model.Tournament.TournamentId" style="color:#087485">Return to Portal</a>
</p>

db8abase/db8abase/Views/TournamentDirectors/Edit.cshtml
@model db8abase.Models.TournamentDirector

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>TournamentDirector</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TournamentDirectorId" />
            <input type="hidden" asp-for="TournamentId" />
            <input type="hidden" asp-for="ApplicationUserId" />
            <input type="hidden" asp-for="SchoolId" />
            <input type="hidden" asp-for="Message" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/TournamentDirectors/GetRoomsList.cshtml
@model IEnumerable<db8abase.Models.Room>

@{
    ViewData["Title"] = "GetRoomsList";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>GetRoomsList</title>
</head>
<body>
    <br />
    <br />
    <h1 style="text-decoration:underline">Rooms List</h1>
    <br />
    <p>
        <a asp-controller="Rooms" asp-action="Create">Add Room</a>
    </p>
    <br />
    <table class="table table-hover">
        <thead>
            <tr class="table-primary">
                <th style="text-decoration:underline">
                    @Html.DisplayNameFor(model => model.RoomNumber)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-secondary">
                    <th scope="row">
                        @Html.DisplayFor(modelItem => item.RoomNumber)
                    </th>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.RoomId">Delete</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <br />
    <br />
    <p>
        <a asp-controller="TournamentDirectors" asp-action="Index">Done Adding Rooms</a>
    </p>
</body>
</html>

db8abase/db8abase/Views/TournamentDirectors/Index.cshtml
@model db8abase.Models.TournamentDirector

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutDirector.cshtml";
}
<br />
<br />
<h1 style="text-align:center;text-decoration:underline"> Welcome @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h1>
<br />
<br />
<div class="row">
    <div class="col-sm-6">
        <h3 style="text-align:center;text-decoration:underline">Tournament Management</h3>
        <br />
        <p style= "text-align:center">
            <a asp-area="" asp-controller="TournamentDirectors" asp-action="CreateTournament" style="color:#087485">Create Tournament</a>
        </p>
        <p style= "text-align:center">
            <a asp-area="" asp-controller="TournamentDirectors" asp-action="Edit" style="color:#087485;">Update Account</a>
        </p>
    </div>
    <div class="col-sm-6">
        <h3 style="text-align:center;text-decoration:underline">Tournament Portal</h3>
        <br />
        <p style= "text-align:center">
            <a asp-area="" asp-controller="TournamentDirectors" asp-action="TournamentPortal" style="color:#087485">Enter Portal</a>
        </p>
    </div>
</div>

db8abase/db8abase/Views/TournamentDirectors/SelectSchool.cshtml
@model db8abase.Models.School

@{
    ViewData["Title"] = "SelectSchool";
}
<br />
<br />
<h3>Click the button to confirm this school selection</h3>
<br />
<p>School: @Html.DisplayFor(model => model.Name)</p>
<br />
<br />
<div>
    <form asp-area="" asp-controller="TournamentDirectors" asp-action="SelectSchool">
        <input type="submit" value="Confirm" class="btn btn-primary" asp-for="SchoolId" />
    </form>
</div>

db8abase/db8abase/Views/TournamentDirectors/TournamentListing.cshtml
@model db8abase.Models.Tournament

@{
    ViewData["Title"] = "TournamentListing";
}

<h1>TournamentListing</h1>


<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TournamentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
            @Html.DisplayNameFor(model => model.NumberOfRounds)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        <tr>
            <td>
                @Html.DisplayFor(model => model.TournamentDate)
            </td>
            <td>
                @Html.DisplayFor(model => model.Name)
            </td>
            <td>
                @Html.DisplayFor(model => model.NumberOfRounds)
            </td>
            <td>
                <a asp-controller="Pairings" asp-action="Tabulate" asp-route-id="@Model.TournamentId">Tabulate</a>
            </td>
        </tr>
    </tbody>
</table>

db8abase/db8abase/Views/TournamentDirectors/ViewIndividualRound.cshtml
@model db8abase.Models.ViewModels.PairingsTabulationViewModel
@{
    ViewData["Title"] = "ViewIndividualRound";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Round 1 Pairing</h1>
<h4 style="text-align:center">@Html.DisplayFor(model => model.Tournament.Name)</h4>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                Room
            </th>
            <th>
                Affirmative
            </th>
            <th>
                Negative
            </th>
            <th>
                Judge
            </th>
            <th>
                Ballot Status
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.AffirmativeTeams.Count(); i++)
        {
            <tr class="table-secondary">
                <th scope="row">
                    @Html.DisplayFor(model => model.Rooms[i].RoomNumber)
                </th>
                <td>
                    @Html.DisplayFor(model => model.AffirmativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NegativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Judges[i].LastName), @Html.DisplayFor(model => model.Judges[i].FirstName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Ballots[i].BallotTurnedIn)
                </td>
            </tr>
        }
    </tbody>
</table>
<p>Click below to return to the portal</p>
<p>
    <a asp-action="TournamentPortal">Tournament Portal</a>
</p>