db8abase/db8abase/Models/Debater.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace db8abase.Models
{
    public class Debater
    {
        [Key]
        public int DebaterId { get; set; }
        [Display(Name = "First Name")]
        public string FirstName { get; set; }
        [Display (Name = "Last Name")]
        public string LastName { get; set; }
        public string Email { get; set; }
        [Display(Name = "Phone Number")]
        public int PhoneNumber {get; set;}
        [ForeignKey("Coach Id")]
        public int CoachId { get; set; }
        [ForeignKey("Debate Partner Id")]
        public int PartnerId { get; set; }
        [ForeignKey("School Id")]
        public int SchoolId { get; set; }
        [ForeignKey("Individual Team Id")]
        public int IndividualTeamId { get; set; }
        public int SpeakerPosition { get; set; }
        public double IndividualTournamentSpeakerPoints { get; set; }
        public double AnnualAverageSpeakerPoints { get; set; }
        [ForeignKey("User Id")]
        public string ApplicationUserId { get; set; }
    }
}

db8abase/db8abase/Controllers/DebatersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using db8abase.Data;
using db8abase.Models;
using System.Security.Claims;
using db8abase.Models.ViewModels;

namespace db8abase.Controllers
{
    public class DebatersController : Controller
    {
        private readonly ApplicationDbContext _context;

        public DebatersController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Debaters
        public async Task<IActionResult> Index()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            Debater debater = _context.Debater.FirstOrDefault(d => d.ApplicationUserId == currentUserId);
            return View(debater);
        }

        // GET: Debaters/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var debater = await _context.Debater
                .FirstOrDefaultAsync(m => m.DebaterId == id);
            if (debater == null)
            {
                return NotFound();
            }

            return View(debater);
        }

        public IActionResult TournamentPairings()
        {
            List<Tournament> tournaments = _context.Tournament.ToList();
            return View(tournaments);
        }

        public IActionResult ViewPairings(int id)
        {
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            Debater debater = _context.Debater.FirstOrDefault(d => d.ApplicationUserId == currentUserId);
            IndividualTeam team = _context.IndividualTeam.FirstOrDefault(i => i.IndividualTeamId == debater.IndividualTeamId);
            List<Pairing> pairings = _context.Pairing.Where(p => p.TournamentId == id && (p.AffirmativeTeamId == team.IndividualTeamId || p.NegativeTeamId == team.IndividualTeamId)).ToList();
            List<Judge> judges = new List<Judge>();
            List<IndividualTeam> affTeams = new List<IndividualTeam>();
            List<IndividualTeam> negTeams = new List<IndividualTeam>();
            List<Room> rooms = new List<Room>();
            List<Round> rounds = new List<Round>();
            foreach(var pair in pairings)
            {
                Judge judge = _context.Judge.FirstOrDefault(j => j.JudgeId == pair.JudgeId);
                judges.Add(judge);
                IndividualTeam affTeam = _context.IndividualTeam.FirstOrDefault(i => i.IndividualTeamId == pair.AffirmativeTeamId);
                affTeams.Add(affTeam);
                IndividualTeam negTeam = _context.IndividualTeam.FirstOrDefault(i => i.IndividualTeamId == pair.NegativeTeamId);
                negTeams.Add(negTeam);
                Room room = _context.Room.FirstOrDefault(r => r.RoomId == pair.RoomId);
                rooms.Add(room);
                Round round = _context.Round.FirstOrDefault(r => r.RoundId == pair.RoundId);
                rounds.Add(round);
            }

            PairingsTabulationViewModel data = new PairingsTabulationViewModel()
            {
                Tournament = tournament,
                Rounds = rounds,
                Rooms = rooms,
                AffirmativeTeams = affTeams,
                NegativeTeams = negTeams,
                Judges = judges,
                Debater = debater,
            };
            return View(data);
        }

        // GET: Debaters/Create
        public IActionResult Create()
        {
            Debater debater = new Debater();
            return View(debater);
        }

        // POST: Debaters/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("DebaterId,FirstName,LastName,Email,PhoneNumber,CoachId,PartnerId,SchoolId,IndividualRoundSpeakerPoints,IndividualTournamentSpeakerPoints,AnnualAverageSpeakerPoints,ApplicationUserId")] Debater debater/*, string Id*/)
        {
            if (ModelState.IsValid)
            {
                //debater.ApplicationUserId = Id;
                var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
                var currentCoach = _context.Coach.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
                debater.CoachId = currentCoach.CoachId;
                debater.SchoolId = currentCoach.SchoolId;
                _context.Add(debater);
                await _context.SaveChangesAsync();
                return RedirectToAction("ManageTeam", "Coaches");
            }
            return View(debater);
        }

        // GET: Debaters/Edit/5
        public IActionResult Edit()
        {
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentUser = _context.Users.FirstOrDefault(u => u.Id == currentUserId);
            Debater debater = _context.Debater.Where(d => d.Email == currentUser.Email).Single();
            debater.ApplicationUserId = currentUserId;
            _context.Update(debater);
            _context.SaveChanges();
            return RedirectToAction("RegistrationConfirmation", "Home");
        }



        // POST: Debaters/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("DebaterId,FirstName,LastName,Email,PhoneNumber,CoachId,PartnerId,SchoolId,IndividualRoundSpeakerPoints,IndividualTournamentSpeakerPoints,AnnualAverageSpeakerPoints,ApplicationUserId")] Debater debater)
        {
            if (id != debater.DebaterId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(debater);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!DebaterExists(debater.DebaterId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("ManageTeam", "Coaches");
            }
            return View(debater);
        }

        // GET: Debaters/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var debater = await _context.Debater
                .FirstOrDefaultAsync(m => m.DebaterId == id);
            if (debater == null)
            {
                return NotFound();
            }

            return View(debater);
        }

        // POST: Debaters/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var debater = await _context.Debater.FindAsync(id);
            _context.Debater.Remove(debater);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool DebaterExists(int id)
        {
            return _context.Debater.Any(e => e.DebaterId == id);
        }
    }
}

db8abase/db8abase/Views/Debaters/Create.cshtml
@model db8abase.Models.Debater

@{
    ViewData["Title"] = "Create";
    Layout = "~/Views/Shared/_LayoutDebater.cshtml";
}

<br />
<br />
<h2 style="text-decoration:underline">Add Debater</h2>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DebaterId" />
            <input type="hidden" asp-for="ApplicationUserId" />
            <input type="hidden" asp-for="PartnerId" />
            <input type="hidden" asp-for="SchoolId" />
            <input type="hidden" asp-for="IndividualTournamentSpeakerPoints" />
            <input type="hidden" asp-for="AnnualAverageSpeakerPoints" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Coaches" asp-action="ManageTeam">Back to List</a>
</div>

db8abase/db8abase/Views/Debaters/Delete.cshtml
@model db8abase.Models.Debater

@{
    ViewData["Title"] = "Delete";
}

<br />

<h3>Are you sure you want to remove this debater from your roster?</h3>
<div>

    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.FirstName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.FirstName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.LastName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="DebaterId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-controller="Coaches" asp-action="ManageTeam">Back to List</a>
    </form>
</div>

db8abase/db8abase/Views/Debaters/Details.cshtml
@model db8abase.Models.Debater

@{
    ViewData["Title"] = "Details";
}
<br />
<h1>Debater Details</h1>

<div>
 
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            Name
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Email)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Email)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.PhoneNumber)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.PhoneNumber)
        </dd>
        <dt class = "col-sm-2">
            Avg. Speaker Points
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AnnualAverageSpeakerPoints)
        </dd>
    </dl>
</div>
<div>
    <a asp-controller="Coaches" asp-action="ManageTeam">Back to List</a>
</div>

db8abase/db8abase/Views/Debaters/Edit.cshtml
@model db8abase.Models.Debater

@{
    ViewData["Title"] = "Edit";
}
<br />
<h1>Edit Debater Information</h1>


<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="DebaterId" />
            <input type="hidden" asp-for="CoachId" />
            <input type="hidden" asp-for="PartnerId" />
            <input type="hidden" asp-for="SchoolId" />
            <input type="hidden" asp-for="IndividualTournamentSpeakerPoints" />
            <input type="hidden" asp-for="AnnualAverageSpeakerPoints" />
            <input type="hidden" asp-for="ApplicationUserId" />
            <div class="form-group">
                <label asp-for="FirstName" class="control-label"></label>
                <input asp-for="FirstName" class="form-control" />
                <span asp-validation-for="FirstName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="LastName" class="control-label"></label>
                <input asp-for="LastName" class="form-control" />
                <span asp-validation-for="LastName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Email" class="control-label"></label>
                <input asp-for="Email" class="form-control" />
                <span asp-validation-for="Email" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PhoneNumber" class="control-label"></label>
                <input asp-for="PhoneNumber" class="form-control" />
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-controller="Coaches" asp-action="ManageTeam">Back to List</a>
</div>

db8abase/db8abase/Views/Debaters/Index.cshtml
@model db8abase.Models.Debater

@{
    ViewData["Title"] = "Index";
}
<br />
<br />
    <h1 style="text-align:center; text-decoration:underline">Welcome @Html.DisplayFor(model => model.FirstName) @Html.DisplayFor(model => model.LastName)</h1>
<br />
<br />
<div class="row">
    <div class="col-sm-5">
        <h3 style="text-align:center; text-decoration:underline">My Pairings</h3>
        <p style="text-align:center"> Click below to view your pairings</p>
        <br />
        <p style="text-align:center">
            <a asp-area="" asp-controller="Debaters" asp-action="TournamentPairings" style="color:#087485">View Pairings</a>
        </p>
    </div>
    <div class="col-sm-2"></div>
    <div class="col-sm-5">
        <h3 style="text-align:center; text-decoration:underline">Debate Tub</h3>
        <p style="text-align:center"> Click below to enter your debate tub</p>
        <br />
        <p style="text-align:center">
            <a asp-area="" asp-controller="Debaters" asp-action="DebateTub" style="color:#087485">Enter Tub</a>
        </p>
    </div>
</div>

db8abase/db8abase/Views/Debaters/TournamentPairings.cshtml
@model IEnumerable<db8abase.Models.Tournament>

@{
    ViewData["Title"] = "TournamentPairings";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Tournament Listing</h1>
<br />
<h3 style="text-align:center;">Click pairing links to see your pairings for each tournament</h3>
<br />
<br />


<table class="table table-hover">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TournamentDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-secondary">
            <th scope="row">
                @Html.DisplayFor(modelItem => item.TournamentDate)
            </th>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                <a asp-action="ViewPairings" asp-route-id="@item.TournamentId" style="color:#087485">Pairings</a>
            </td>
        </tr>
}
    </tbody>
</table>

db8abase/db8abase/Views/Debaters/ViewPairings.cshtml
@model db8abase.Models.ViewModels.PairingsTabulationViewModel
@{
    ViewData["Title"] = "ViewPairings";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Pairings for: @Html.DisplayFor(model => model.Debater.FirstName) @Html.DisplayFor(model => model.Debater.LastName)</h1>
<h4 style="text-align:center">@Html.DisplayFor(model => model.Tournament.Name)</h4>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                Round
            </th>
            <th>
                Room
            </th>
            <th>
                Affirmative
            </th>
            <th>
                Negative
            </th>
            <th>
                Judge
            </th>
            <th>
                Philosophy
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.AffirmativeTeams.Count(); i++)
        {
            <tr class="table-secondary">
                <th scope="row">
                    @Html.DisplayFor(model => model.Rounds[i].RoundNumber)
                </th>
                <td>
                    @Html.DisplayFor(model => model.Rooms[i].RoomNumber)
                </td>
                <td>
                    @Html.DisplayFor(model => model.AffirmativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NegativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Judges[i].LastName), @Html.DisplayFor(model => model.Judges[i].FirstName)
                </td>
                <td>
                    <a asp-controller="Home" asp-action="ViewPhilosophy" asp-route-id="@Model.Judges[i].JudgeId" style="color:#087485">Philosophy</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>Click below to return to the tournament listing</p>
<p>
    <a asp-controller="Debaters" asp-action="TournamentPairings" style="color:#087485">Back to Portal</a>
</p>