db8abase/db8abase/Models/School.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace db8abase.Models
{
    public class School
    {
        [Key]
        public int SchoolId { get; set; }
        public string Name { get; set; }
        [ForeignKey("Address Id")]
        public int AddressId { get; set; }
        public Address Address { get; set; }

        [ForeignKey("Tournament Director Id")]
        public int TournamentDirectorId { get; set; }
        [ForeignKey("Coach Id")]
        public int CoachId { get; set; }
    }
}

db8abase/db8abase/Controllers/SchoolsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using db8abase.Data;
using db8abase.Models;
using System.Security.Claims;
using db8abase.Utility;
using Newtonsoft.Json;
using System.Net;

namespace db8abase.Controllers
{
    public class SchoolsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public SchoolsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Schools
        public async Task<IActionResult> Index()
        {
            return View(await _context.School.ToListAsync());
        }

        // GET: Schools/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School
                .FirstOrDefaultAsync(m => m.SchoolId == id);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }
        // GET: ListOfSchools
        public IActionResult GetListOfSchools()
        {
            List<School> listOfSchools = _context.School.ToList();
            return View(listOfSchools);
        }

        public string ConvertAddressToGoogleFormat(Address address)
        {
            string googleFormatAddress = address.StreetAddress + "," + address.City + "," + address.StateAbbreviation + "," + address.ZipCode + "," + address.Country;
            return googleFormatAddress;
        }

        public GeoCode GeoLocate(string address)
        {
            var key = Keys.GoogleGeoCodeAPIKey;
            var requestUrl = $"https://maps.googleapis.com/maps/api/geocode/json?address={address}&key={key}";
            var result = new WebClient().DownloadString(requestUrl);
            GeoCode geocode = JsonConvert.DeserializeObject<GeoCode>(result);
            return geocode;
        }

        // GET: Schools/Create
        public IActionResult Create()
        {
            School school = new School();
            return View(school);
        }


        // POST: Schools/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SchoolId,Name,TournamentDirectorId,CoachId,Address")] School school)
        {
            if (ModelState.IsValid)
            {
                var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
                var directorRoleId = _context.Roles.FirstOrDefault(r => r.Name == "TournamentDirector");
                var coachRoleId = _context.Roles.FirstOrDefault(r => r.Name == "Coach");
                var currentUserRole = _context.UserRoles.FirstOrDefault(u => u.UserId == currentUserId);
                if(currentUserRole.RoleId == directorRoleId.Id)
                {
                    var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
                    school.TournamentDirectorId = currentDirector.TournamentDirectorId;
                    Address address = new Address();
                    address = school.Address;
                    address.Country = "USA";
                    string addressToConvert = ConvertAddressToGoogleFormat(address);
                    var geoLocate = GeoLocate(addressToConvert);
                    address.Longitude = geoLocate.results[0].geometry.location.lng;
                    address.Latitude = geoLocate.results[0].geometry.location.lat;
                    _context.Add(school);
                    _context.Add(address);
                    await _context.SaveChangesAsync();
                    school.AddressId = address.AddressId;
                    _context.Update(school);
                    currentDirector.SchoolId = school.SchoolId;
                    _context.Update(currentDirector);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "TournamentDirectors");
                }
                else if(currentUserRole.RoleId == coachRoleId.Id)
                {
                    var currentCoach = _context.Coach.FirstOrDefault(c => c.ApplicationUserId == currentUserId);
                    school.CoachId = currentCoach.CoachId;
                    Address address = new Address();
                    address = school.Address;
                    address.Country = "USA";
                    string addressToConvert = ConvertAddressToGoogleFormat(address);
                    var geoLocate = GeoLocate(addressToConvert);
                    address.Longitude = geoLocate.results[0].geometry.location.lng;
                    address.Latitude = geoLocate.results[0].geometry.location.lat;
                    _context.Add(school);
                    _context.Add(address);
                    await _context.SaveChangesAsync();
                    school.AddressId = address.AddressId;
                    _context.Update(school);
                    currentCoach.SchoolId = school.SchoolId;
                    _context.Update(currentCoach);
                    await _context.SaveChangesAsync();
                    return RedirectToAction("Index", "Coaches");
                }
                else
                {
                    return RedirectToAction("GetTournamentListing", "Home");
                }
            }
            return View(school);
        }


        // GET: Schools/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School.FindAsync(id);
            if (school == null)
            {
                return NotFound();
            }
            return View(school);
        }

        // POST: Schools/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("SchoolId,Name,TournamentDirectorId,CoachId")] School school)
        {
            if (id != school.SchoolId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(school);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SchoolExists(school.SchoolId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(school);
        }

        // GET: Schools/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var school = await _context.School
                .FirstOrDefaultAsync(m => m.SchoolId == id);
            if (school == null)
            {
                return NotFound();
            }

            return View(school);
        }

        // POST: Schools/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var school = await _context.School.FindAsync(id);
            _context.School.Remove(school);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SchoolExists(int id)
        {
            return _context.School.Any(e => e.SchoolId == id);
        }
    }
}

db8abase/db8abase/Views/Schools/Create.cshtml
@model db8abase.Models.School

@{
    ViewData["Title"] = "Create";

}
<br />

<h1 style="text-decoration:underline">Create New School</h1>
<br />
<br />

<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="TournamentDirectorId">
            <input type="hidden" asp-for="CoachId">
            <input type="hidden" asp-for="AddressId">
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.StreetAddress" class="control-label"></label>
                <input asp-for="Address.StreetAddress" class="form-control" />
                <span asp-validation-for="Address.StreetAddress" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.City" class="control-label"></label>
                <input asp-for="Address.City" class="form-control" />
                <span asp-validation-for="Address.City" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.StateAbbreviation" class="control-label"></label>
                <input asp-for="Address.StateAbbreviation" class="form-control" />
                <span asp-validation-for="Address.StateAbbreviation" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address.ZipCode" class="control-label"></label>
                <input asp-for="Address.ZipCode" class="form-control" />
                <span asp-validation-for="Address.ZipCode" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

db8abase/db8abase/Views/Schools/Delete.cshtml
@model db8abase.Models.School

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>School</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TournamentDirectorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TournamentDirectorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoachId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoachId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SchoolId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

db8abase/db8abase/Views/Schools/Details.cshtml
@model db8abase.Models.School

@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Details</h1>

<div>
    <h4>School</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TournamentDirectorId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TournamentDirectorId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CoachId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CoachId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SchoolId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/Schools/Edit.cshtml
@model db8abase.Models.School

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Edit</h1>

<h4>School</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SchoolId" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="TournamentDirectorId" class="control-label"></label>
                <input asp-for="TournamentDirectorId" class="form-control" />
                <span asp-validation-for="TournamentDirectorId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CoachId" class="control-label"></label>
                <input asp-for="CoachId" class="form-control" />
                <span asp-validation-for="CoachId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/Schools/GetListOfSchools.cshtml
@model IEnumerable<db8abase.Models.School>

@{
    ViewData["Title"] = "GetListOfSchools";
}
<br />
<br />
<h1 style="text-align: center; text-decoration: underline">Select Your School Affiliation</h1>
<br />
<h5>If your school is not listed in the table, click the create button at the bottom of the page</h5>
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th style="text-align:center; text-decoration:underline">
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr class="table-secondary">
            <th scope="row">
                @Html.DisplayFor(modelItem => item.Name)
            </th>
            <td>
                @if (this.User.IsInRole("TournamentDirector"))
                {
                    <a asp-controller="TournamentDirectors" asp-action="SelectSchool" asp-route-id="@item.SchoolId" style="color:#087485">Select</a>
                }
                else if (this.User.IsInRole("Coach"))
                {
                    <a asp-controller="Coaches" asp-action="SelectSchool" asp-route-id="@item.SchoolId" style="color:#087485">Select</a>
                }
                else if (this.User.IsInRole("Judge"))
                {
                    <a asp-controller="Judges" asp-action="SelectSchool" asp-route-id="@item.SchoolId" style="color:#087485">Select</a>
                }
                else if (this.User.IsInRole("Debater"))
                {
                    <a asp-controller="Debaters" asp-action="SelectSchool" asp-route-id="@item.SchoolId" style="color:#087485">Select</a>
                }
            </td>
        </tr>
}
    </tbody>
</table>
<br />
<br />
<p>
    <a asp-area="" asp-controller="Schools" asp-action="Create">Create New School</a>
</p>

db8abase/db8abase/Views/Schools/Index.cshtml
@model IEnumerable<db8abase.Models.School>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.TournamentDirectorId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.CoachId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.TournamentDirectorId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.CoachId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.SchoolId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.SchoolId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.SchoolId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>