db8abase/db8abase/Models/Pairing.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace db8abase.Models
{
    public class Pairing
    {
        [Key]
        public int PairingId { get; set; }
        [ForeignKey("Tournament Id")]
        public int TournamentId { get; set; }
        [ForeignKey("Judge Id")]
        public int JudgeId { get; set; }
        [ForeignKey("Room Id")]
        public int RoomId { get; set; }
        [ForeignKey("Affirmative Team")]
        public int AffirmativeTeamId { get; set; }
        [ForeignKey("Negative Team")]
        public int NegativeTeamId { get; set; }
        [ForeignKey("Round Id")]
        public int RoundId { get; set; }
        [ForeignKey("Debate Id")]
        public int DebateId { get; set; }
        [ForeignKey("Winner Id")]
        public int WinnerId { get; set; }
    }
}

db8abase/db8abase/Controllers/PairingsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using db8abase.Data;
using db8abase.Models;
using db8abase.Models.ViewModels;
using System.Security.Claims;
using MimeKit;
using MailKit.Net.Smtp;

namespace db8abase.Controllers
{
    public class PairingsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public PairingsController(ApplicationDbContext context)
        {
            _context = context;
        }

        // GET: Pairings
        public async Task<IActionResult> Index()
        {
            return View(await _context.Pairing.ToListAsync());
        }

        // GET: Tabulate
        public IActionResult Tabulate(int id)
        {
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
            return View(tournament);
        }

        public void SendPairingEmailToJudge(string lastName, string firstName, string emailAddress, IndividualTeam team1, IndividualTeam team2, Room room)
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("Name", "devcodecampsweepstakes@gmail.com"));
            message.To.Add(new MailboxAddress(lastName, emailAddress));
            message.Subject = "Judging assignment";

            message.Body = new TextPart("plain")
            {
                Text = $@"{firstName} {lastName},

You are scheduled to judge this round.  Your debate will be in {room.RoomNumber}.

You will be judging {team1.IndividualTeamName} and {team2.IndividualTeamName}.
Let the Tournament Director know if you have any questions.



Thank you."
            };

            using (var client = new SmtpClient())
            {
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect("smtp.gmail.com", 587, false);

                client.Authenticate("devcodecampsweepstakes", "Cc283192");

                client.Send(message);
                client.Disconnect(true);
            }
        }

        public void SendPairingEmailToDebater(string lastName, string firstName, string emailAddress, IndividualTeam opponent, Room room, Judge judge)
        {
            var message = new MimeMessage();
            message.From.Add(new MailboxAddress("Name", "devcodecampsweepstakes@gmail.com"));
            message.To.Add(new MailboxAddress(lastName, emailAddress));
            message.Subject = "Judging assignment";

            message.Body = new TextPart("plain")
            {
                Text = $@"{firstName} {lastName},

You are scheduled to debate this round.  Your debate will be in {room.RoomNumber}.

You will be facing {opponent.IndividualTeamName} and your judge is {judge.FirstName} {judge.LastName}.
Let the Tournament Director know if you have any questions.



Thank you."
            };

            using (var client = new SmtpClient())
            {
                client.ServerCertificateValidationCallback = (s, c, h, e) => true;

                client.Connect("smtp.gmail.com", 587, false);

                client.Authenticate("devcodecampsweepstakes", "Cc283192");

                client.Send(message);
                client.Disconnect(true);
            }
        }

        public IActionResult ViewRoundDetails(int id)
        {
            List<Ballot> ballots = GetBallots(id);
            var currentUserId = this.User.FindFirstValue(ClaimTypes.NameIdentifier).ToString();
            var currentDirector = _context.TournamentDirector.FirstOrDefault(t => t.ApplicationUserId == currentUserId);
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == currentDirector.TournamentId);
            List<Room> rooms = GetRooms(currentDirector.TournamentId);
            List<IndividualTeam> affirmativeTeams = GetRoundAffTeams(id);
            List<IndividualTeam> negativeTeams = GetRoundNegTeams(id);
            List<Judge> judges = GetRoundJudges(id);

            PairingsTabulationViewModel viewModelData = new PairingsTabulationViewModel()
            {
                Tournament = tournament,
                Rooms = rooms,
                AffirmativeTeams = affirmativeTeams,
                NegativeTeams = negativeTeams,
                Judges = judges,
                Ballots = ballots,
            };
            return View(viewModelData);
        }
        public List<IndividualTeam> GetRoundAffTeams(int id)
        {
            List<Pairing> roundPairing = _context.Pairing.Where(p => p.RoundId == id).ToList();
            List<IndividualTeam> roundAffTeams = new List<IndividualTeam>();
            for(int i = 0; i < roundPairing.Count(); i++)
            {
                IndividualTeam team = _context.IndividualTeam.FirstOrDefault(t => t.IndividualTeamId == roundPairing[i].AffirmativeTeamId);
                roundAffTeams.Add(team);
            }
            return roundAffTeams;
        }
        public List<IndividualTeam> GetRoundNegTeams(int id)
        {
            List<Pairing> roundPairing = _context.Pairing.Where(p => p.RoundId == id).ToList();
            List<IndividualTeam> roundNegTeams = new List<IndividualTeam>();
            for (int i = 0; i < roundPairing.Count(); i++)
            {
                IndividualTeam team = _context.IndividualTeam.FirstOrDefault(t => t.IndividualTeamId == roundPairing[i].NegativeTeamId);
                roundNegTeams.Add(team);
            }
            return roundNegTeams;
        }
        public List<Judge> GetRoundJudges(int id)
        {
            List<Pairing> roundPairing = _context.Pairing.Where(p => p.RoundId == id).ToList();
            List<Judge> judges = new List<Judge>();
            for (int i = 0; i < roundPairing.Count(); i++)
            {
                Judge judge = _context.Judge.FirstOrDefault(t => t.JudgeId == roundPairing[i].JudgeId);
                judges.Add(judge);
            }
            return judges;
        }

        public List<Ballot> GetBallots(int id)
        {
            List<Ballot> ballots = _context.Ballot.Where(b => b.RoundId == id).ToList();
            return ballots;
        }
        // GET: PairRoundOne
        public IActionResult PairRoundOne(int id)
        {
            
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
            List<Room> rooms = GetRooms(id);
            List<IndividualTeam> affirmativeTeams = GetRoundOneAffirmativeTeams(id);
            List<IndividualTeam> negativeTeams = GetRoundOneNegativeTeams(id);
            List<Judge> judges = AssignRoundOneJudges(id);

            PairingsTabulationViewModel viewModelData = new PairingsTabulationViewModel()
            {
                Tournament = tournament,
                Rooms = rooms,
                AffirmativeTeams = affirmativeTeams,
                NegativeTeams = negativeTeams,
                Judges = judges,
            };
            return View(viewModelData);
        }

        public IActionResult PairingsView(int id)
        {
            Tournament tournament = _context.Tournament.FirstOrDefault(t => t.TournamentId == id);
            List<Room> rooms = GetRooms(id);
            List<IndividualTeam> affirmativeTeams = GetRoundOneAffirmativeTeams(id);
            List<IndividualTeam> negativeTeams = GetRoundOneNegativeTeams(id);
            List<Judge> judges = AssignRoundOneJudges(id);

            PairingsTabulationViewModel viewModelData = new PairingsTabulationViewModel()
            {
                Tournament = tournament,
                Rooms = rooms,
                AffirmativeTeams = affirmativeTeams,
                NegativeTeams = negativeTeams,
                Judges = judges,
            };
            return View(viewModelData);
        }
        public void PushRoundOnePairing(int id)
        {
            Round round = CreateRoundOne(id);
            CreateRoundOneDebate(id);
            List<IndividualTeam> affirmativeTeams = GetRoundOneAffirmativeTeams(id);
            List<IndividualTeam> negativeTeams = GetRoundOneNegativeTeams(id);
            List<Judge> judges = AssignRoundOneJudges(id);
            List<Room> rooms = GetRooms(id);
            int j = 0;
            foreach(var judge in judges)
            {
                SendPairingEmailToJudge(judge.LastName, judge.FirstName, judge.Email, affirmativeTeams[j], negativeTeams[j], rooms[j]);
                j++;
            }
            for(int i = 0; i < affirmativeTeams.Count(); i++)
            {
                IndividualTeam affTeam = affirmativeTeams[i];
                IndividualTeam negTeam = negativeTeams[i];
                Pairing pairing = new Pairing();
                pairing.TournamentId = id;
                pairing.RoundId = round.RoundId;
                pairing.AffirmativeTeamId = affirmativeTeams[i].IndividualTeamId;
                pairing.NegativeTeamId = negativeTeams[i].IndividualTeamId;
                pairing.JudgeId = judges[i].JudgeId;
                pairing.RoomId = rooms[i].RoomId;
                pairing.DebateId = _context.Debate.Where(d => d.JudgeId == pairing.JudgeId && d.AffirmativeTeamId == pairing.AffirmativeTeamId && d.NegativeTeamId == pairing.NegativeTeamId && d.RoomId == pairing.RoomId).Single().DebateId;
                affTeam.TournamentAffirmativeRounds++;
                negTeam.TournamentNegativeRounds++;
                _context.Add(pairing);
                _context.Update(affTeam);
                _context.Update(negTeam);
                _context.SaveChanges();
            }
        }

        public List<IndividualTeam> FindDueNegTeams(int id)
        {
            var teams = GetTeams(id);
            List<IndividualTeam> dueNegTeams = new List<IndividualTeam>();
            foreach(var team in teams)
            {

db8abase/db8abase/Views/Pairings/Create.cshtml
@model db8abase.Models.Pairing

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Pairing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="TournamentId" class="control-label"></label>
                <input asp-for="TournamentId" class="form-control" />
                <span asp-validation-for="TournamentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JudgeId" class="control-label"></label>
                <input asp-for="JudgeId" class="form-control" />
                <span asp-validation-for="JudgeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <input asp-for="RoomId" class="form-control" />
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AffirmativeTeamId" class="control-label"></label>
                <input asp-for="AffirmativeTeamId" class="form-control" />
                <span asp-validation-for="AffirmativeTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegativeTeamId" class="control-label"></label>
                <input asp-for="NegativeTeamId" class="form-control" />
                <span asp-validation-for="NegativeTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoundId" class="control-label"></label>
                <input asp-for="RoundId" class="form-control" />
                <span asp-validation-for="RoundId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DebateId" class="control-label"></label>
                <input asp-for="DebateId" class="form-control" />
                <span asp-validation-for="DebateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/Pairings/Delete.cshtml
@model db8abase.Models.Pairing

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Pairing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TournamentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TournamentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AffirmativeTeamId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AffirmativeTeamId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegativeTeamId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegativeTeamId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoundId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoundId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DebateId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DebateId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="PairingId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

db8abase/db8abase/Views/Pairings/Details.cshtml
@model db8abase.Models.Pairing

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Pairing</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.TournamentId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.TournamentId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.JudgeId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.JudgeId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoomId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoomId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.AffirmativeTeamId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.AffirmativeTeamId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.NegativeTeamId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.NegativeTeamId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RoundId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.RoundId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.DebateId)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.DebateId)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.PairingId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/Pairings/Edit.cshtml
@model db8abase.Models.Pairing

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Pairing</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="PairingId" />
            <div class="form-group">
                <label asp-for="TournamentId" class="control-label"></label>
                <input asp-for="TournamentId" class="form-control" />
                <span asp-validation-for="TournamentId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="JudgeId" class="control-label"></label>
                <input asp-for="JudgeId" class="form-control" />
                <span asp-validation-for="JudgeId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoomId" class="control-label"></label>
                <input asp-for="RoomId" class="form-control" />
                <span asp-validation-for="RoomId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="AffirmativeTeamId" class="control-label"></label>
                <input asp-for="AffirmativeTeamId" class="form-control" />
                <span asp-validation-for="AffirmativeTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="NegativeTeamId" class="control-label"></label>
                <input asp-for="NegativeTeamId" class="form-control" />
                <span asp-validation-for="NegativeTeamId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="RoundId" class="control-label"></label>
                <input asp-for="RoundId" class="form-control" />
                <span asp-validation-for="RoundId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="DebateId" class="control-label"></label>
                <input asp-for="DebateId" class="form-control" />
                <span asp-validation-for="DebateId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

db8abase/db8abase/Views/Pairings/Index.cshtml
@model IEnumerable<db8abase.Models.Pairing>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.TournamentId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.JudgeId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoomId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.AffirmativeTeamId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NegativeTeamId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RoundId)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DebateId)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.TournamentId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.JudgeId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoomId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.AffirmativeTeamId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.NegativeTeamId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RoundId)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.DebateId)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.PairingId">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.PairingId">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.PairingId">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

db8abase/db8abase/Views/Pairings/PairRoundFour.cshtml
@model db8abase.Models.ViewModels.PairingsTabulationViewModel
@{
    ViewData["Title"] = "PairRoundFour";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Round 4 Pairing</h1>
<h4 style="text-align:center">@Html.DisplayFor(model => model.Tournament.Name)</h4>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                Room
            </th>
            <th>
                Affirmative
            </th>
            <th>
                Negative
            </th>
            <th>
                Judge
            </th>
            <th>
                Philosophy
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.AffirmativeTeams.Count(); i++)
        {
            <tr class="table-secondary">
                <th scope="row">
                    @Html.DisplayFor(model => model.Rooms[i].RoomNumber)
                </th>
                <td>
                    @Html.DisplayFor(model => model.AffirmativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NegativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Judges[i].LastName), @Html.DisplayFor(model => model.Judges[i].FirstName)
                </td>
                <td>
                    <a asp-controller="Home" asp-action="ViewPhilosophy" asp-route-id="@Model.Judges[i].JudgeId" style="color:#087485">Philosophy</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>Fourth round pairings have been successfully sent with the above information.  Click below to return to Tournament Portal</p>
<p>
    <a asp-controller="TournamentDirectors" asp-action="TournamentPortal" style="color:#087485">Back to Portal</a>
</p>
</p>

db8abase/db8abase/Views/Pairings/PairRoundOne.cshtml
@model db8abase.Models.ViewModels.PairingsTabulationViewModel
@{
    ViewData["Title"] = "PairRoundOne";
}

<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>PairRoundOne</title>
</head>
<body>
    <br />
    <br />
    <h1 style="text-align:center; text-decoration:underline">Round 1 Pairing</h1>
    <h4 style="text-align:center">@Html.DisplayFor(model => model.Tournament.Name)</h4>
    <br />
    <br />
    <table class="table table-hover">
        <thead>
            <tr class="table-primary">
                <th>
                    Room
                </th>
                <th>
                    Affirmative
                </th>
                <th>
                    Negative
                </th>
                <th>
                    Judge
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @for (int i = 0; i < Model.AffirmativeTeams.Count(); i++)
            {
                <tr class="table-secondary">
                    <th scope="row">
                        @Html.DisplayFor(model => model.Rooms[i].RoomNumber)
                    </th>
                    <td>
                        @Html.DisplayFor(model => model.AffirmativeTeams[i].IndividualTeamName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.NegativeTeams[i].IndividualTeamName)
                    </td>
                    <td>
                        @Html.DisplayFor(model => model.Judges[i].LastName), @Html.DisplayFor(model => model.Judges[i].FirstName)
                    </td>
                    <td>
                        <a asp-controller="Home" asp-action="ViewPhilosophy" asp-route-id="@Model.Judges[i].JudgeId" style="color:#087485">Philosophy</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <p>Click below to send out first round pairings</p>
    <p>
        <a asp-controller="Pairings" asp-action="SendRoundOnePairing" asp-route-id="@Model.Tournament.TournamentId" style="color:#087485">Send Pairings</a>
    </p>
</body>
</html>

db8abase/db8abase/Views/Pairings/PairRoundThree.cshtml
@model db8abase.Models.ViewModels.PairingsTabulationViewModel
@{
    ViewData["Title"] = "PairRoundThree";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Round 3 Pairing</h1>
<h4 style="text-align:center">@Html.DisplayFor(model => model.Tournament.Name)</h4>
<br />
<br />
<table class="table table-hover">
    <thead>
        <tr class="table-primary">
            <th>
                Room
            </th>
            <th>
                Affirmative
            </th>
            <th>
                Negative
            </th>
            <th>
                Judge
            </th>
            <th>
                Philosophy
            </th>
        </tr>
    </thead>
    <tbody>
        @for (int i = 0; i < Model.AffirmativeTeams.Count(); i++)
        {
            <tr class="table-secondary">
                <th scope="row">
                    @Html.DisplayFor(model => model.Rooms[i].RoomNumber)
                </th>
                <td>
                    @Html.DisplayFor(model => model.AffirmativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.NegativeTeams[i].IndividualTeamName)
                </td>
                <td>
                    @Html.DisplayFor(model => model.Judges[i].LastName), @Html.DisplayFor(model => model.Judges[i].FirstName)
                </td>
                <td>
                    <a asp-controller="Home" asp-action="ViewPhilosophy" asp-route-id="@Model.Judges[i].JudgeId" style="color:#087485">Philosophy</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<p>Third round pairings have been successfully sent with the above information.  Click below to return to Tournament Portal</p>
<p>
    <a asp-controller="TournamentDirectors" asp-action="TournamentPortal" style="color:#087485">Return to Portal</a>
</p>
</p>

db8abase/db8abase/Views/Pairings/Results.cshtml
@model IEnumerable<db8abase.Models.Tournament>

    @{
        ViewData["Title"] = "Results";
    }
    <br />
    <br />
    <h1 style="text-align:center; text-decoration:underline">Tournament Listing</h1>
    <br />
    <h3 style="text-align:center;">Click the results link to below to see results for that tournament</h3>
    <br />
    <br />


    <table class="table table-hover">
        <thead>
            <tr class="table-primary">
                <th>
                    @Html.DisplayNameFor(model => model.TournamentDate)
                </th>
                <th>
                    @Html.DisplayNameFor(model => model.Name)
                </th>
                <th></th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="table-secondary">
                    <th scope="row">
                        @Html.DisplayFor(modelItem => item.TournamentDate)
                    </th>
                    <td>
                        @Html.DisplayFor(modelItem => item.Name)
                    </td>
                    <td>
                        <a asp-action="ViewResults" asp-route-id="@item.TournamentId" style="color:#087485">Results</a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

db8abase/db8abase/Views/Pairings/Tabulate.cshtml
@model db8abase.Models.Tournament
@{
    ViewData["Title"] = "Tabulate";
}
<br />
<br />
<h1 style="text-align:center; text-decoration:underline">Tabulate</h1>
<br />
<br />
<p style="text-align:center">Click the link below to generate pairings for Round 1</p>
<br />
<p style="text-align:center">
    <a asp-controller="Pairings" asp-action="PairRoundOne" asp-route-id="@Model.TournamentId">Pair Round One</a>
</p>